### ISSUE TITLE
Can this plugin replace metalsmith-branch?

### ISSUE THREAD

**Issue by ghost** [deltamualpha/metalsmith-if#2]
I've been running into several issues with `metalsmith-branch`, and it doesn't seem to be actively maintained. Could this plugin possibly replace the file-based filtering that `metalsmith-branch` did?

**Comment by deltamualpha** [comment]
It depends on your specific setup, but I think no, in the general case. This plugin substitutes another plugin for itself at compile time, but doesn't do so for each file. Can you post the relevant parts of your metalsmith build step?

**Comment by ghost** [comment]
I have two build scripts, but here's one: [serve.js](https://github.com/ismay/ismaywolff.nl/blob/master/serve.js).

I'm filtering files by filetype to speed up the build, and prevent any unexpected behaviour. But unfortunately `metalsmith-branch` doesn't seem to like certain plugins (like `filenames` and `rename` for example), which I then have to move outside of the branch (see [here](https://github.com/ismay/ismaywolff.nl/blob/master/serve.js#L87-L95)).

Branch also fails without any errors, which makes it hard to debug. I'd open an issue there, but it's not under active development, which is why I'm looking for a replacement. However, I couldn't find any documentation/examples on whether `metalsmith-if` can filter by filetype, so that's why I opened this issue.

**Comment by deltamualpha** [comment]
Hmm, I don't think so. `if()` is basically an on/off switch instead of a per-file router.

You might have to write a function inline that loops over the filelist and then passes some subset into a plugin... perhaps like this? Pseudocode using lodash's filter:

``` js
m.use(function(files, metalsmith, done) {
  metalsmith = metalsmith.use(
    some_other_plugin(_.filter(files, function_testing_for_minimatch))
  );
  done();
})
```

I'm not sure about that internal metalsmith reassignment, but the metalsmith object passed to plugins is the complete object, so that in theory should work. That's how I'd approach it to start, anyway.

**Comment by ghost** [comment]
Ok cool, thanks for the example. I'll see if I can create a PR that fixes the issues for `metalsmith-branch`.

**Comment by deltamualpha** [comment]
I'm not sure `metalsmith-branch` is worth saving -- it was designed for a _very_ early version of metalsmith. Maybe just start from scratch?

**Comment by ghost** [comment]
Yeah, it'll probably be a complete rewrite, but I think the name makes sense and I don't want to create confusion by having too many similar plugins. If the owner doesn't want to merge I can always publish a new plugin.
