### ISSUE TITLE
Support function for conditional

### ISSUE THREAD

**Issue by devinus** [deltamualpha/metalsmith-if#4]
E.g.

``` js
function isProduction(env) {
  return env === 'production';
}

msIf(isProduction, plugin)
```

**Comment by deltamualpha** [comment]
What would the behavior be? This test, for example, already passes.

``` js
  var falseFun = function(){
    return false;
  };

  it('should accept a function as the conditional', function(done){
    var m = Metalsmith('test/fixture')
      .use(msIf(falseFun(),
        ran()
      ));
    m.build(function(err){
      if (err) { console.log(err); }
      assert(exists('test/fixture/build'));
      assert(!m.metadata().ran);
      done();
    });
  });
```

**Comment by devinus** [comment]
It does not accept a function, it's eagerly executing the function so the function is never passed. The test would have to look like this:

``` js
  var falseFun = function(){
    return false;
  };

  it('should accept a function as the conditional', function(done){
    var m = Metalsmith('test/fixture')
      .use(msIf(falseFun,
        ran()
      ));
    m.build(function(err){
      if (err) { console.log(err); }
      assert(exists('test/fixture/build'));
      assert(!m.metadata().ran);
      done();
    });
  });
```

**Comment by deltamualpha** [comment]
OK, simple enough to implement, but what's the use case?

**Comment by devinus** [comment]
@deltamualpha sometimes you want to lazily compute whether the plugin should be run or not based on the current environment.

**Comment by deltamualpha** [comment]
One last puzzler, then: what's the 'current environment' -- the `metalsmith` object?

**Comment by devinus** [comment]
@deltamualpha It could be anything, but in my case it is the `process.env`. Passing in the `metalsmith` object would be interesting. I can see usecases with the metadata.

**Comment by deltamualpha** [comment]
OK, then does this interface make sense? I'm not a javascript expert.

`msIf(conditional, function, [optional object to pass to the conditional])`

**Comment by devinus** [comment]
@deltamualpha I think `msIf(conditional: Boolean | Function)` is a good enough API.

The `conditional` is a `Function`, you can `Function.call` it with the `Metalsmith` object itself. E.g. `conditional.call(conditional, metalsmithObject)`

**Comment by deltamualpha** [comment]
@devinus Ah, but the plugin doesn't have access to that; it only returns a function that later gets called with the metalsmith object, so the conditional function's arguments would have be passed in explicitly. And that still only ever runs at call time, not plugin execution time, so there's no practical difference between `if(funct(foo), maybe())` and `if(funct, maybe(), foo)`.

The only way to get real run-time conditionals would be to attempt to parse the `metalsmith.plugins` object and add/remove items from the list.

**Comment by devinus** [comment]
@deltamualpha Ah, indeed. Well that was just a nice bonus if it could be supported.

**Comment by deltamualpha** [comment]
I'd consider a PR, but probably won't put in the work.

This ends up performing something similar, if someone wants to, say, evaluate the existing metalsmith object using a function as the conditional:

``` js
var m = new Metalsmith(dir);
m.use(msIf(conditional(m), maybe()));
m.build();
```
