### ISSUE TITLE
Metalsmith org adoption proposal - @metalsmith/if

### ISSUE THREAD

**Issue by webketje** [deltamualpha/metalsmith-if#5]
Hi there,

In a new effort to consolidate the metalsmith ecosystem under the Github and NPM metalsmith orgs, 
I'm reaching out to authors of contributed plugins that are so common in metalsmith builds, they could be considered *core plugins* and would add value to the Metalsmith org.
The proposal is as follows:

- I invite you as a collaborator to the metalsmith org so you can transfer the repository. The repository will be renamed to `<plugin>` instead of `metalsmith-<plugin>` (the full url will then be `https://github.com/metalsmith/<plugin>`).
- After an initial (non-opinionated) dev setup alignment (dotfiles, changelog, readme format), you can choose to stay in the org and maintain the plugin if you wish, including releasing on NPM, or forfeit maintenance to the metalsmith org members. A deprecation notice would need to be pushed to `https://npmjs.com/package/metalsmith-<plugin>` and the plugin will be republished as `@metalsmith/<plugin>`.
- Your authorship will be aknowledged in the `README.md`.  The copyright to the plugin remains yours, unless you decide to transfer the rights to [webketje](https://kbopub.economie.fgov.be/kbopub/toonondernemingps.html?lang=en&ondernemingsnummer=759463478), copyright owner of metalsmith since Sept. 2021. If you transfer the copyright, the LICENSE would look like this:
```
Copyright (c) 2021 webketje
Copyright (c) 2015-2021 David Ashby
```

**Comment by deltamualpha** [comment]
I would be amenable to moving `if` into the `metalsmith` organization, and continuing as a maintainer. (Sorry it took me so long to respond!)

**Comment by webketje** [comment]
NP, no rush.. 
With the advent of MS2.5 and the `metalsmith.env` method a week ago, this plugin could also easily be made compatible with the CLI (metalsmith.json) flow like 
```json
{
  "@metalsmith/if": [
    "$PRODUCTION",
    "metalsmith-other-plugin": {
       "option": "value"
    }
  ]
}
```
The plugin code would do sth. like:
```js
let condition = arg
if (metalsmith.env('cli') && arg.startsWith('$')) {
  condition = metalsmith.env(arg.slice(1))
}
// rest of the code
```

**Comment by webketje** [comment]
Closing this issue & revoking the request since:
- the latest release does not align to `metalsmith.debug`
- the functionality provided by this plugin is only useful to the CLI but it is not CLI-compatible, e.g. in JS one can easily do:
```js
// allows multiple use calls to be grouped in 1 check
if (!isDev) metalsmith.use(someProductionPlugin())

// or
function noop() {}

metalsmith.use(isDev ? noop : someProductionPlugin())
```

**Comment by deltamualpha** [comment]
Can you clarify what you mean by "does not align to metalsmith.debug"? I'm happy to change the plugin to work with more recent metalsmith versions, but a pointer to the documentation on that would be helpful.

And yes, the plugin is indeed very simple and could be implemented by any developer. But it's also one of the most popular metalsmith plugins on NPM by pull count, it looks like, so clearly there's some folks out there finding it useful. I'm not much of a JS developer and haven't used metalsmith myself in nearly a decade, but again, would be happy to upgrade it to be useful from the CLI if pointed to some documentation on how to do that.

**Comment by webketje** [comment]
Feel free but not obliged. I tried to convey that I think this plugin is not necessarily the best way to solve using plugins conditionally, see https://metalsmith.io/docs/usage-guide/#conditionally-running-plugins and no longer think it should be a core plugin. Here's the docs about plugin debug logs: https://metalsmith.io/docs/writing-plugins/#adding-debug-logs-to-the-plugin.
If you are interested, the release posts will get you caught up fast https://metalsmith.io/news/
